version: "3.9"

x-airflow-common: &airflow-common
  image: apache/airflow:3.0.2
  environment:
    _PIP_ADDITIONAL_REQUIREMENTS: "apache-airflow-providers-http==5.3.0"
  volumes:
    - ./dags:/opt/airflow/dags
  depends_on:
    - postgres

services:
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports: [ "port:port" ]

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  
  airflow-worker:
    <<: *airflow-common
    command: celery

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports: [ "port:port" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: